In [1]:
import pandas as pd
df = pd.read_pickle(r"D:\2026_Summer\TradingApp\data\v3.0\all_symbol_min_full_main_close_k_1.pkl"); df

,trading_date,close,open,high,low,volume,total_turnover,open_interest,contract,underlying_symbol,K
datetime,,,,,,,,,,,
2010-01-04 09:00:00,2010-01-04,4080.0,4080.0,4080.0,4080.0,700.0,28560000.0,138699.0,A1009,A,0.929102
2010-01-04 09:01:00,2010-01-04,4080.0,4080.0,4086.0,4075.0,4012.0,163746650.0,139717.0,A1009,A,0.929102
2010-01-04 09:02:00,2010-01-04,4073.0,4080.0,4080.0,4072.0,1909.0,77792780.0,139291.0,A1009,A,0.929102
2010-01-04 09:03:00,2010-01-04,4079.0,4073.0,4079.0,4073.0,1484.0,60479200.0,139291.0,A1009,A,0.929102
2010-01-04 09:04:00,2010-01-04,4075.0,4079.0,4080.0,4075.0,1446.0,58966160.0,139843.0,A1009,A,0.929102
...,...,...,...,...,...,...,...,...,...,...,...
2026-07-29 14:56:00,2026-07-29,24775.0,24775.0,24775.0,24770.0,373.0,46203375.0,105455.0,ZN2609,ZN,0.882097
2026-07-29 14:57:00,2026-07-29,24780.0,24775.0,24780.0,24770.0,229.0,28370625.0,105455.0,ZN2609,ZN,0.882097
2026-07-29 14:58:00,2026-07-29,24770.0,24780.0,24780.0,24765.0,232.0,28738125.0,105443.0,ZN2609,ZN,0.882097
2026-07-29 14:59:00,2026-07-29,24770.0,24770.0,24770.0,24760.0,515.0,63771600.0,105312.0,ZN2609,ZN,0.882097
2026-07-29 15:00:00,2026-07-29,24765.0,24765.0,24770.0,24765.0,502.0,62163775.0,105165.0,ZN2609,ZN,0.882097

In [2]:
d = df[(df['underlying_symbol'] == 'AU') & (df['trading_date'] == '2025-10-09')].sort_index()

print(d.shape)          # (556, 11)
print(d.index.min(), '->', d.index.max()) 
with pd.option_context('display.max_rows', None, 'display.width', 200):
    display(d)

(556, 11)
2025-10-08 21:00:00 -> 2025-10-09 15:00:00

                    trading_date   close    open    high     low  volume  total_turnover  open_interest contract underlying_symbol         K
datetime
2025-10-08 21:00:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:01:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:02:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:03:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:04:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:05:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:06:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:07:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:08:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:09:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:10:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:11:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:12:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:13:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:14:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:15:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:16:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:17:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:18:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:19:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:20:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:21:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:22:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:23:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:24:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:25:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:26:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:27:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:28:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:29:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:30:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:31:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:32:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:33:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:34:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:35:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:36:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:37:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:38:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:39:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:40:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:41:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:42:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:43:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:44:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:45:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:46:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:47:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:48:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:49:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:50:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:51:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:52:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:53:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:54:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:55:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:56:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:57:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:58:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 21:59:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:00:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:01:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:02:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:03:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:04:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:05:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:06:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:07:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:08:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:09:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:10:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:11:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:12:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:13:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:14:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:15:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:16:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:17:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:18:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:19:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:20:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:21:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:22:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:23:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:24:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:25:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:26:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:27:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:28:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:29:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:30:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:31:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:32:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:33:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:34:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:35:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:36:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:37:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:38:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:39:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:40:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:41:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:42:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:43:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:44:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:45:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:46:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:47:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:48:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:49:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:50:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:51:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:52:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:53:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:54:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:55:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:56:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:57:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:58:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 22:59:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 23:00:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 23:01:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 23:02:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 23:03:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 23:04:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 23:05:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 23:06:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 23:07:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 23:08:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 23:09:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 23:10:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 23:11:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 23:12:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 23:13:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 23:14:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 23:15:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 23:16:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 23:17:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 23:18:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691
2025-10-08 23:19:00   2025-10-09  874.40  874.40  874.40  874.40     0.0    0.000000e+00       256876.0   AU2512                AU  1.286691

In [2]:
df.info(memory_usage='deep')

<class 'pandas.DataFrame'>
DatetimeIndex: 66284866 entries, 2010-01-04 09:00:00 to 2026-07-29 15:00:00
Data columns (total 11 columns):
 #   Column             Dtype
---  ------             -----
 0   trading_date       datetime64[ns]
 1   close              float64
 2   open               float64
 3   high               float64
 4   low                float64
 5   volume             float64
 6   total_turnover     float64
 7   open_interest      float64
 8   contract           object
 9   underlying_symbol  object
 10  K                  float64
dtypes: datetime64[ns](1), float64(8), object(2)
memory usage: 11.5 GB

In [3]:
df.iloc[0:2100]

,trading_date,close,open,high,low,volume,total_turnover,open_interest,contract,underlying_symbol,K
datetime,,,,,,,,,,,
2010-01-04 09:00:00,2010-01-04,4080.0,4080.0,4080.0,4080.0,700.0,28560000.0,138699.0,A1009,A,0.929102
2010-01-04 09:01:00,2010-01-04,4080.0,4080.0,4086.0,4075.0,4012.0,163746650.0,139717.0,A1009,A,0.929102
2010-01-04 09:02:00,2010-01-04,4073.0,4080.0,4080.0,4072.0,1909.0,77792780.0,139291.0,A1009,A,0.929102
2010-01-04 09:03:00,2010-01-04,4079.0,4073.0,4079.0,4073.0,1484.0,60479200.0,139291.0,A1009,A,0.929102
2010-01-04 09:04:00,2010-01-04,4075.0,4079.0,4080.0,4075.0,1446.0,58966160.0,139843.0,A1009,A,0.929102
...,...,...,...,...,...,...,...,...,...,...,...
2010-01-15 10:01:00,2010-01-15,3935.0,3934.0,3935.0,3933.0,453.0,17823810.0,134427.0,A1009,A,0.929102
2010-01-15 10:02:00,2010-01-15,3936.0,3935.0,3937.0,3935.0,1125.0,44278550.0,134338.0,A1009,A,0.929102
2010-01-15 10:03:00,2010-01-15,3936.0,3937.0,3937.0,3935.0,475.0,18696410.0,134275.0,A1009,A,0.929102
2010-01-15 10:04:00,2010-01-15,3938.0,3936.0,3938.0,3936.0,327.0,12874210.0,134332.0,A1009,A,0.929102
2010-01-15 10:05:00,2010-01-15,3936.0,3938.0,3938.0,3936.0,289.0,11377180.0,134400.0,A1009,A,0.929102

In [4]:
icc=df.groupby('underlying_symbol').agg(n=('close','size'),
    start=('trading_date','min'), end=('trading_date','max'))
icc.iloc[0:50]

                         n      start        end
underlying_symbol
A                  1277250 2010-01-04 2026-07-29
AG                 1786964 2012-05-16 2026-07-29
AL                 1614722 2010-01-04 2026-07-29
AO                   92237 2023-06-27 2024-04-22
AP                  468950 2017-12-28 2026-07-29
AU                 1916010 2010-01-04 2026-07-29
B                  1277250 2010-01-04 2026-07-29
BB                  664666 2013-12-12 2026-01-16
BC                  636698 2020-11-25 2026-07-29
BR                   60204 2023-08-03 2024-04-22
BU                 1064314 2013-10-15 2026-07-29
C                  1111440 2010-01-04 2026-07-29
CF                 1269000 2010-01-04 2026-07-29
CJ                  395048 2019-05-09 2026-07-29
CS                  838658 2014-12-25 2026-07-29
CU                 1614722 2010-01-04 2026-07-29
CY                  753468 2017-08-24 2026-07-29
EB                  561074 2019-10-09 2026-07-29
EC                   35708 2023-08-24 2024-04-22
EG                  619664 2018-12-14 2026-07-29
FB                  656982 2013-12-12 2026-01-16
FG                 1090688 2012-12-07 2026-07-29
FU                  661718 2018-07-20 2026-07-29
HC                 1039228 2014-03-27 2026-07-29
I                  1069782 2013-10-24 2026-07-29
IC                  664084 2015-04-22 2026-07-29
IF                  992265 2010-04-22 2026-07-29
IH                  664084 2015-04-22 2026-07-29
IM                  101220 2022-07-28 2024-04-22
J                  1245348 2011-04-21 2026-07-29
JD                  696984 2013-11-14 2026-07-29
JM                 1100292 2013-03-28 2026-07-29
JR                  815634 2013-11-22 2026-01-16
L                  1111440 2010-01-04 2026-07-29
LC                   40228 2023-07-27 2024-04-22
LH                  301710 2021-01-14 2026-07-29
LR                  760038 2014-07-14 2025-12-31
LU                  507978 2020-06-30 2026-07-29
M                  1277250 2010-01-04 2026-07-29
MA                 1168656 2011-11-03 2026-07-29
NI                 1254860 2015-04-02 2026-07-29
NR                  571906 2019-08-16 2026-07-29
OI                 1251600 2010-01-04 2026-07-29
P                  1315860 2010-01-04 2026-07-29
PB                 1547374 2011-03-30 2026-07-29
PF                  483186 2020-10-16 2026-07-29
PG                  524834 2020-04-03 2026-07-29
PK                  298094 2021-02-05 2026-07-29
PM                  909198 2010-01-04 2026-01-16
PP                  883858 2014-03-06 2026-07-29

In [5]:
icc.iloc[50:-1]

                         n      start        end
underlying_symbol
PX                   48094 2023-09-21 2024-04-22
RB                 1270200 2010-01-04 2026-07-29
RI                  908972 2010-01-04 2026-01-16
RM                 1103794 2013-01-08 2026-07-29
RR                  570521 2019-08-22 2026-07-29
RS                  714838 2013-01-08 2026-01-16
RU                 1232280 2010-01-04 2026-07-29
SA                  545158 2019-12-12 2026-07-29
SC                 1091978 2018-03-30 2026-07-29
SF                  655174 2014-08-14 2026-07-29
SH                   48094 2023-09-21 2024-04-22
SI                   71642 2022-12-28 2024-04-22
SM                  655174 2014-08-14 2026-07-29
SN                 1254860 2015-04-02 2026-07-29
SP                  630818 2018-12-03 2026-07-29
SR                 1269000 2010-01-04 2026-07-29
SS                  749700 2019-10-08 2026-07-29
T                   723952 2015-03-26 2026-07-29
TA                 1269000 2010-01-04 2026-07-29
TF                  824222 2013-09-12 2026-07-29
TL                   60928 2023-04-27 2024-04-22
TS                  497396 2018-08-23 2026-07-29
UR                  379454 2019-08-15 2026-07-29
V                  1111440 2010-01-04 2026-07-29
WH                 1021294 2010-01-04 2026-01-16
WR                  424880 2018-10-22 2026-07-29
Y                  1277250 2010-01-04 2026-07-29
ZC                 1195605 2013-10-09 2026-01-16

In [11]:
s = df.groupby(['underlying_symbol','trading_date'])['contract'].nunique()
s[s != 1]

underlying_symbol  trading_date
JR                 2024-07-02      2
                   2024-07-03      3
                   2024-07-04      4
                   2024-07-05      4
                   2024-07-08      4
                                  ..
ZC                 2025-03-12      5
                   2025-03-13      4
                   2025-03-14      3
                   2025-03-17      3
                   2025-03-18      2
Name: contract, Length: 814, dtype: int64

In [12]:
bad = s[s != 1]
bad.index.get_level_values(0).value_counts()        # 集中在几个品种，还是全品种?
bad.groupby(level=0).agg(size='size', mx='max')     # 每个品种坏几天、最多几路并列

                   size  mx
underlying_symbol
JR                  172   5
LR                  211   4
PM                   47   4
RI                   47   4
WH                  210   5
ZC                  127   7

In [13]:
sym, dt = bad.index[0]
df[(df.underlying_symbol == sym) & (df.trading_date == dt)][
    ['contract', 'volume', 'open_interest', 'close']
]

                    contract  volume  open_interest   close
datetime
2024-07-02 09:00:00   JR2503     0.0            0.0  2662.0
2024-07-02 09:00:00   JR2411     0.0            0.0  2662.0
2024-07-02 09:01:00   JR2411     0.0            0.0  2662.0
2024-07-02 09:01:00   JR2503     0.0            0.0  2662.0
2024-07-02 09:02:00   JR2411     0.0            0.0  2662.0
...                      ...     ...            ...     ...
2024-07-02 14:58:00   JR2503     0.0            0.0  2662.0
2024-07-02 14:59:00   JR2411     0.0            0.0  2662.0
2024-07-02 14:59:00   JR2503     0.0            0.0  2662.0
2024-07-02 15:00:00   JR2503     0.0            0.0  2662.0
2024-07-02 15:00:00   JR2411     0.0            0.0  2662.0

[452 rows x 4 columns]

In [27]:
night = df[df.index.hour >= 20]
(pd.to_datetime(night['trading_date']) > night.index.normalize()).mean()

np.float64(1.0)

In [31]:
df.groupby(['underlying_symbol','trading_date'])['contract'].nunique() == 1

underlying_symbol  trading_date
A                  2010-01-04      True
                   2010-01-05      True
                   2010-01-06      True
                   2010-01-07      True
                   2010-01-08      True
                                   ...
ZN                 2026-07-23      True
                   2026-07-24      True
                   2026-07-27      True
                   2026-07-28      True
                   2026-07-29      True
Name: contract, Length: 208394, dtype: bool